version: "3"

services:
  app:
    build: 
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db # name of the database service
      - DB_NAME=app # same as the POSTGRES_DB name
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on: # list of depengind services
      - db # this means the 'db' service will start BEFORE this (app) service
  
  db:
    image: postgres:10-alpine
    environment: # environment variables list
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword