version: "3"

services:
  nginx:
    build: ./nginx
    volumes:
      - ../static:/vol/web/static
      - ../media:/vol/web/media
    ports:
      - 1337:80
    depends_on:
      - app

  app:
    build: 
      context: .
    volumes:
      - ./app:/app
      - ../static:/vol/web/static
      - ../media:/vol/web/media
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py collectstatic --no-input --clear &&
            gunicorn app.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on: # list of depengind services
      - db # this means the 'db' service will start BEFORE this (app) service

  db:
    image: postgres:10-alpine
    environment: # environment variables list
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
