version: "3"

services:
  app:
    build: 
      context: .
    volumes:
      - ./app:/app
      - ../media:/vol/web/media
    command: >
      sh -c "python manage.py wait_for_db &&
            gunicorn app.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on: # list of depengind services
      - db # this means the 'db' service will start BEFORE this (app) service
  
  db:
    image: postgres:10-alpine
    environment: # environment variables list
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
