# Generated by Django 2.2.3 on 2019-07-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190727_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='filename',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='link',
            field=models.CharField(max_length=255),
        ),
    ]
