# Generated by Django 2.2.3 on 2019-07-29 13:20

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190727_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('x_axis', models.CharField(max_length=255)),
                ('y_axis', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('result_file', models.FileField(unique=True, upload_to=core.models.resultfile_file_path)),
                ('link', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Experiment')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Measurement')),
                ('nuwroversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Nuwroversion')),
            ],
        ),
    ]
