# Generated by Django 2.2.3 on 2019-07-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_resultfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultfile',
            name='related_datafiles',
            field=models.ManyToManyField(to='core.Datafile'),
        ),
    ]
