# Generated by Django 2.2.7 on 2019-11-15 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_resultfile_related_datafiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafile',
            name='x_axis',
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='y_axis',
        ),
    ]
