# Generated by Django 2.2.7 on 2019-11-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191115_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultfile',
            name='is_3d',
            field=models.BooleanField(default=False),
        ),
    ]
