# Generated by Django 2.2.6 on 2019-12-15 20:49

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_resultfile_is_3d'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=core.models.artifact_file_path)),
                ('link', models.CharField(max_length=255)),
                ('addition_date', models.DateTimeField(auto_now_add=True)),
                ('resultfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Resultfile')),
            ],
        ),
    ]
