# Generated by Django 2.2.6 on 2019-12-15 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20191215_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artifact',
            old_name='file',
            new_name='artifact',
        ),
    ]
