# Generated by Django 2.2.6 on 2019-12-16 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20191215_2123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Datafile',
        ),
    ]
