# Generated by Django 2.2.6 on 2020-02-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_delete_datafile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resultfile',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
