# Generated by Django 2.2.6 on 2021-01-03 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200203_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultfile',
            name='x_axis',
        ),
        migrations.RemoveField(
            model_name='resultfile',
            name='y_axis',
        ),
        migrations.RemoveField(
            model_name='resultfile',
            name='z_axis',
        ),
    ]
