# Generated by Django 2.2.6 on 2021-01-06 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210103_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='resultfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='core.Resultfile'),
        ),
    ]
